### PR TITLE
update version numbers for plugins

### PR DESCRIPTION
**Pull request by Bulmenisaurus**
I just changed everything to 0.6.4 for everything except for claim-best, so there might be some other round 3 only plugins

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Lets try it, we can fix later if need. THANKS!

**Comment by phated** [comment]
The template wasn't updated, so these are going to all be marked as the red label

**Comment by phated** [comment]
Screen Shot 2021-09-30 at 12 40 09 PM

**Comment by jacobrosenthal** [comment]
Yeah does it matter? What color should they be? Green is prettier I guess

**Comment by phated** [comment]
Yes, they are supposed to be green. The green blends into the border indicating that they are g2g - red is a stark contrast because those are bad/old/broken plugins.

**Comment by phated** [comment]
I think this should be reverted. Plugins for 0.6 are supposed to work across versions. The API stability was the reason for the push to these long-lived versions with rounds.

**Comment by jacobrosenthal** [comment]
I dont think thats a plugins repo problem, thats a core game broke semver problem

**Comment by phated** [comment]
👍 Just trying to make a suggestion based on the work I did. You own this so handle it however you want. If you are going to keep this change, you probably want to fix the template 🤷

**Comment by jacobrosenthal** [comment]
Im just trying to understand your point of view. I think maybe your statement is that you wish for someone playing the literal 6.0 round 1 version of the game to be able to come here and understand that all those (now 6.4) versions actually work on that game. I think true and valuable, though fairly rare. Its more likely someone comes here and tries to find something thats going to work for the version of the game theyre playing (6.4) right now

What does fixing the template mean to you, and how could we do it

**Comment by phated** [comment]
> What does fixing the template mean to you, and how could we do it

Easiest change would be to grep 0.6.0 and replace with 0.6.4

**Comment by jacobrosenthal** [comment]
So again, tryingto understand. 
For you, bg-red means bad scary dont use this. Its not just a different color to differentiate?
so bg-green should always track the current version of the game?

**Comment by phated** [comment]
The original design was that 0.6.0 would track all plugins for all 0.6.x (maybe I should have used that schema) and those would show the version support in green (good) while all older 0.5.0 versions would be marked in red until people updated them.

**Comment by phated** [comment]
FWIW, I was pretty sure we were on the same page about this because you had MJ remove his 0.6.2 version updates in one of his PRs. Like I said, feel free to do what you want.

**Comment by jacobrosenthal** [comment]
If I recall correctly I had someone remove their 6.2 because at the time that plugin was no different from any of the other ones so there was no reason to differentiate it and it only added confusion. 

I think another solution at the time would have been to move everything to 6.2 but I chose 6.0 with the hope that core would be additive.

Now in this case I feel like Im held to the breaking change made in core, and am forced to move everything to 6.4 to reduce confusion

**Pull request merged**
