### PR TITLE
Revert "Add new Artifacts Finder plugin and Fix Artifactory issue (#96)"

### PR DESCRIPTION
**Pull request by phated**
This reverts commit 0d9192d16382354f37cbad0e838de55705b889ad.

This reverts #96 because it broke the artifactory imports that I **just** fixed.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Is there a reason it should be reverted, and not simple imported with your new style. Also would you like to document all imports must by sync

**Comment by phated** [comment]
> Also would you like to document all imports must by sync

No ESM is sync. Top-level dynamic import is new and doesn't work in every browser.

**Comment by phated** [comment]
Happy to not revert if @snowtigersoft or you want to update the imports

**Comment by jacobrosenthal** [comment]
Oh I dont mean tell me I mean we have a contribution guide where we try to maintain a list of things like this that can be checked against incoming prs.

Also its not particularly important that you *just* fixed anything. This is a community repo, everyone is doing their best.

**Comment by phated** [comment]
> Also its not particularly important that you just fixed anything.

It is, because you supposedly reviewed and gave me the run-around. I specifically called it out in the commit for you and then you accepted a PR that un-did the changes.

**Comment by phated** [comment]
I removed all of the formatting changes that fucked up the artifactory diff and fixed all of the imports and force pushed over that commit. So we don't need this anymore.

**Comment by snowtigersoft** [comment]
@phated @jacobrosenthal Sorry to trouble you, I will pay attention to these in the future.
The format problem is because I used it myself, and habitually used the format function comes with idea, which default tab setting to 4 spaces.
@phated Sorry for wast you a lot of time to fix this kind of simple problems

**Pull request closed without merging**
