### PR TITLE
add plugin map-filter-export

### PR DESCRIPTION
**Pull request by DfArchonX**
Only export the 16x16 pixel blocks that have filtered planets.
 
the speed of export and import is faster :-)   
 
notice 1: If the number of planets is too large, the website may crash, so we recommend choose a reasonable planetLevel range, such as [3,9]. We don't recommend to choose the planetLevel 0, because the planets's amount maybe very large.
         
notice 2: When export the map which has a lot of 16x16 pixel blocks, the import speed is fast, but you may need to wait the planets to show up for a while. Click the button [Show Planets] and Use the middle mouse button to zoom in and out may help to make the planets show up more quickly.

 When writing this plugin, we learn a lot from the plugin named map export, Thanks to the authors of map export !

### CODE REVIEW

**Comment by ichub** [comment]
I just tested this, and it appears that the plugin exports only planets, not the entire map data. i.e. when i zoom into a region of space with important planets, i only see planets, no background. was that intentional?

**Comment by DfArchonX** [comment]
> I just tested this, and it appears that the plugin exports only planets, not the entire map data. i.e. when i zoom into a region of space with important planets, i only see planets, no background. was that intentional?

yes, the plugin only have 16x16 block to show planets, the map file is too big with the background.

**Comment by cristobal** [comment]
@DfArchonX perhaps one should be able to toggle on/off this as mode if one wants to export the planets and not rest of the (which is cleary slower), but i think otherwise the current behaviour of the plugin is modifying the existing expected behaviour. 

While if exporting only the planets is an option the plugin would still offer the same mechanics as before but rather allowing people to self choose if they want to export only the planets or not.

**Comment by ichub** [comment]
I could go either way on this. I think an alternative I would also accept is a strong disclaimer that this only exports planets, not background chunks.

**Comment by DfArchonX** [comment]
we choose to have two buttons [ export with background] and [export without background].

**Review by cristobal — APPROVED** [review]
LGTM 👍

**Comment by cristobal** [comment]
> we choose to have two buttons [ export with background] and [export without background].

Nice 👍

**Review by ichub — APPROVED** [review]
tested locally and it worked!

**Pull request merged**
