### PR TITLE
Updates voyage-time to v0.6

### PR DESCRIPTION
**Pull request by gabeio**

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Looks good I think. And I think `getTimeForMove` should respect wormholes so we should be good there too right?

**Comment by gabeio** [comment]
> I think getTimeForMove should respect wormholes so we should be good there too right?

@jacobrosenthal It seems to, I am able to get estimates to wormholes just fine.

**Comment by gabeio** [comment]
Screen Shot 2021-05-31 at 17 34 04

**Review by phated — APPROVED** [review]
Excellent! Thank you!

**Pull request merged**
