### PR TITLE
updated for v 0.6

### PR DESCRIPTION
**Pull request by MJ659600**
Only needed to change the last line to 
export default Plugin;

### CODE REVIEW

**Comment by phated** [comment]
Hmm, the `import` shouldn't work 🤔

**Comment by phated** [comment]
Try changing the `import` statement to this:
```js
import { html, render, useState, useLayoutEffect } from 'https://unpkg.com/htm/preact/standalone.module.js';
```

**Comment by MJ659600** [comment]
strange.  worked as is when I tested.Will make the change when I settle down from travel ( in a day or so)Sent from my Galaxy
-------- Original message --------From: Blaine Bublitz ***@***.***> Date: 5/20/21  8:07 PM  (GMT-05:00) To: darkforest-eth/plugins ***@***.***> Cc: MJ659600 ***@***.***>, Author ***@***.***> Subject: Re: [darkforest-eth/plugins] updated for v 0.6 (#53) 
Try changing the import statement to this:
import { html, render, useState, useLayoutEffect } from 'https://unpkg.com/htm/preact/standalone.module.js';

**Comment by MJ659600** [comment]
Strange: worked well on my Chrome before and after changing the import line.

**Review by phated — APPROVED** [review]
Excellent! I've updated the metadata to mark this as v0.6.0-ready!

**Comment by phated** [comment]
> Strange: worked well on my Chrome before and after changing the import line.

There's an in-progress JS proposal to allow "top level await" which is to have the `await` syntax outside of an `async function`, so maybe your browser has that feature. I'm just trying to be careful to support users that don't have that feature.

**Comment by MJ659600** [comment]
Thanks all!Sent from my Galaxy
-------- Original message --------From: Blaine Bublitz ***@***.***> Date: 5/21/21  12:42 PM  (GMT-05:00) To: darkforest-eth/plugins ***@***.***> Cc: MJ659600 ***@***.***>, Author ***@***.***> Subject: Re: [darkforest-eth/plugins] updated for v 0.6 (#53) 
@phated approved this pull request.

Excellent! I've updated the metadata to mark this as v0.6.0-ready!

**Pull request merged**
