### PR TITLE
Mini-Map Plugin Submission

### PR DESCRIPTION
**Pull request by nicholashc**
Submission for DF v0.5 Community Plugins Contest.

This plugin samples a grid of points across the entire map, determines the space type at each point, and renders a mini-map with a rough terrain map of nebulas and deep space.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Amazing stuff. 
Id love to see a smaller version, or trivially resizeable version with hardcoded size at the top if need be.

Feature requests :) feel free to take or leave
- Draw a square for the current viewport. People get lost on their mini map.
- Make it clickable. Do the math to roughly guess where Im clicking and use ui.centerCoords() to move viewport there.
- Render large (>5?) planets/asteroids on the map with their color. It helps to visually anchor yourself, `oh, ok so its between my lvl7 and the guy on my east sides llv6`
- Indicate fog of war. Slightly grey? areas where I cant see to match the full map when you zoom out. again really helps with anchoring. `Oh theres deep space right to the right of where I stopped mining 2 days ago by my level7'

**Comment by nicholashc** [comment]
great feedback! i'll see what i can incorporate

**Comment by jacobrosenthal** [comment]
You got more coming? Should we merge yet?

**Comment by nicholashc** [comment]
This is all I have for the time being. Merge away!

**Pull request merged**
