### PR TITLE
Performance Optimizer

### PR DESCRIPTION
**Pull request by adietrichs**
# Performance Optimizer

Aims to improve performance under heavy load:

* Reduce render load by limiting percentage of total compute power to spend on rendering. Currently implemented very naively by overwriting `window.requestAnimationFrame`. Could be more sophisiticated in the future if render managers get exposed. Also, limited FPS mode disabled for now as it somehow doesn't work.
* Cache move zk-SNARK proofs. This seems like it could be (in a more optimized form) added to the native game, as it really doesn't have any downsides. Every move between the same two planets after the first one is sped up significantly. Would need somewhat cleverer storage management if it were to be added persistently - currently reset on game launch.

### CODE REVIEW

**Comment by adietrichs** [comment]
Updated plugin with bugfixes (the `window.requestAnimationFrame` modification should not cause any issues anymore). This also fixed fps mode, which is now enabled.

**Comment by Bind** [comment]
Howdy! I'm also overwriting the .getMoveArgs call in a different plugin, I'd love to leverage a shared cache here. Could you hang the zkcache object and maybe a moveArgsToKey function off of the window object? Thanks!

**Comment by jacobrosenthal** [comment]
ping @adietrichs

**Comment by phated** [comment]
I'd be fine just merging this and then taking another PR to do what @Bind asked for (also testing it myself and it is sick!)

**Comment by adietrichs** [comment]
> Howdy! I'm also overwriting the .getMoveArgs call in a different plugin, I'd love to leverage a shared cache here. Could you hang the zkcache object and maybe a moveArgsToKey function off of the window object? Thanks!

Sorry, only seeing that now. Would love to find a way to make these compatible! I think we have to be careful though to ensure this works in either combination and order of plugin execution, especially given that we both overwrite `getMoveArgs`. Happy to look into that tomorrow. Do you have a link to your plugin or is that still WIP?

> I'd be fine just merging this and then taking another PR to do what @Bind asked for (also testing it myself and it is sick!)

Either way would be fine with me.

**Comment by Bind** [comment]
Just pushed up a PR with what I [currently have](https://github.com/darkforest-eth/plugins/pull/37/files). If my plugin is run first, things will work just fine as you're wrapping the native call. Things get wonky if your's is run first as I need to replace the getMoveArgs call completely in order to call out to the remote server. We could keep it simple and I can re-implement the caching logic in my plugin in such a way that the cache counter gets bumped in your plugin if it's exposed or we could try and figure out a more generalizable way to share the move call execution. Could be something like middleware. 

Either way, great plugin! 🚀

**Pull request merged**
