### PR TITLE
Add plugin: Highlight Buffs

### PR DESCRIPTION
**Pull request by davidryan59**
I have developed a plugin to highlight all the 2x buffs (energy, energy growth, defense, range, speed), and highlight all the artifacts (on or off the original foundry) and spacetime rips.

This was started during Dark Forest v0.6 Round 3, I didn't finish the plugin by the end of the round, but now a week later I feel it is ready to submit to the team.

Uses for the plugin:
- Exploring a new territory and easily locating planets with extra range or speed, to go farther / faster
- Mopping up an existing territory and figuring out where all the artifacts are, and how to get them to the spacetime rips
- Going a bit crazy with colour and animation (go on! you know you want to)

I've attached a couple of screenshots below. They show the same planets, but with different display options. I have included 8 on/off display options, which give up to 256 total option combinations (but due to duplication, a few less than 256).

Hope you see fit to include this in the Dark Forest plugins repository! I had fun making it - David Ryan (dryan.eth, https://twitter.com/davidryan59)

Screenshot 2021-08-28 at 19 07 39
Screenshot 2021-08-28 at 19 08 12

### CODE REVIEW

**Comment by Velorum6** [comment]
Just tested it and works great, good job!

Maybe some suggestions for the future if you want to continue developing it:

- Would be cool to be able to filter by type of planets, since when you search for x2 buffs you also search for upgrades bcs these upgrades will be buffed x2 too, is not the same an asteroid field with his base x2 range buff than a planet of the same level with +4 upgrades on range with x2 buff.

- When loading L0-L9 planets with a x2 buff the game almost crash trying to highlight all the planets, maybe you can add a limitation to just highlight the planets of a specified zone, like the range-attack plugin of rootial https://github.com/darkforest-eth/plugins/blob/master/content/productivity/range-attack/plugin.js

**Review by Stx69 — APPROVED** [review]

**Comment by davidryan59** [comment]
@Velorum6

Yes, limited range (or possibly highlight count) is a great idea for players with large maps. I will get working on adding that, expect it within a few days!

Regarding your other comment "Would be cool to be able to filter by type of planets, since when you search for x2 buffs you also search for upgrades bcs these upgrades will be buffed x2 too, is not the same an asteroid field with his base x2 range buff than a planet of the same level with +4 upgrades on range with x2 buff."

There is a lot in your comment, but would the following satisfy the requirements:
- Dropdown filter on which planet types to highlight, something like ALL / Planet / Asteroid / Rip / Foundry / Quasar
- 2 dropdowns on min rank / max rank (Rank 0, Rank 1, ... Rank 5)

Of course upgrades get complex because there are 3 types - defense, speed, range - are you saying you want me to combine the search for 2x buffs with Xx defense/speed/range upgrades?

**Comment by davidryan59** [comment]
I've got the range filter working. The planet filter should be straightforward. Had to do some refactoring of selects. Will updated PR when done!

**Comment by davidryan59** [comment]
@Velorum6 I have added:
- Range filter (between 1000 and 999999 in world coords)
- Planet Type filter (all types, or only 1 of the 5)
- Upgrades to Defense, Speed or Range are now highlighted along with the 2x buff
- UI improvements and reorganisation
- Backend refactoring

How is it now? Hope it is not crashing your large map any more?

Happy to merge PR and add plugin to main repo if you are. Thanks - David

**Comment by Velorum6** [comment]
Just tested it, it doesn't crash, the filter you added is very useful to only track a specified type of planets and the range selection to search in the place you are looking is great.

Definetively a plugin that I would use for the next round, you did a good job.

**Review by Velorum6 — APPROVED** [review]

**Comment by davidryan59** [comment]
Thanks @Velorum6! I appreciate the positive review and comments. I also will find this plugin useful in the next round!

**Review by Stx69 — APPROVED** [review]

**Review by jacobrosenthal — COMMENTED** [review]
The screenshot is half a meg! Definitely need that to be like 20-50kb

**Comment by davidryan59** [comment]
@jacobrosenthal - I have reduced screenshot size down to 37 kB. Is that OK?

**Comment by jacobrosenthal** [comment]
Yes thanks. Love the animation options!
Thank you @Velorum6 for the reviews too

**Comment by davidryan59** [comment]
Thanks @jacobrosenthal for merging, glad you like the animation! Look forward to seeing all the buffs in Round 4 :)

**Pull request merged**
