### PR TITLE
feat: Add SilverSpacetime plugin

### PR DESCRIPTION
**Pull request by phated**
This plugin has a bunch of overlap with Distribute Silver but I wanted to add automatic sending, the problem was that it caused a bunch of network congestion in 0.6 Round 1.

In order to deal with that, I added a bunch of controls to adjust how much you wanted to congest and it grew too large for that plugin.

This also contains an automatic withdraw feature.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Can you talk about what some good configuration was for you for the v6 round1 and  why you need to limit at all. I presume it has to do with out of memory limits and or rpc limits

**Comment by phated** [comment]
> why you need to limit at all. I presume it has to do with out of memory limits and or rpc limits

The issues center around the changes made to the "events" system - the game no longer does anything with events and instead tries to replay logs and then forcibly ("hardRefresh") refresh data. It caused a ton of JSON-RPC requests to queue up and either the public xdai endpoints couldn't handle it or the browser doesn't allow that many in-flight requests.

I have some client patches to lighten that load, but haven't upstreamed yet.

>  Can you talk about what some good configuration was for you for the v6 round1 and

While I slept, I ran it with 0 pending and 10 queued, but that can be adjusted upward and then you can hard refresh the browser after all the moves queued.

**Comment by jacobrosenthal** [comment]
Sorry. Can you put something in the description. " If the game crashes to a
black screen you've set your pending moves to high.  On a MacBook pro I was
able to use 22 for v6 round 1"

**Comment by phated** [comment]
Where are you getting this? My game has never crashed from snarking or Txs this round. The issue this is dealing with is cascading refreshes, which is mentioned.

**Comment by jacobrosenthal** [comment]
Sure I can keep trying. 

Im a downstream user of your plugin. It has max pending moves, and max moves to queue. I do not understand why. How would I know if I had  "congestion" without talking to my primary care physician. Is there an error message? And when Im experiencing congestion for more than 3 hours. Do I change max pending moves or max moves to queue?

**Comment by phated** [comment]
There's really no way to know. This took me days of investigating deep in the client. You just don't see shit happening - it's the stuff that people have been complaining about all round.

**Comment by phated** [comment]
Going to merge this.

**Pull request merged**
