### PR TITLE
Plugin pattern improvements

### PR DESCRIPTION
**Pull request by phated**
This is a ~WIP~ PR for updating the plugin patterns to more up-to-date patterns.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Is the version released for this yet? Or is it going to be the first 6.3 release?

**Comment by phated** [comment]
Yes, these are released

**Comment by phated** [comment]
Alright, this is an absolutely massive cleanup of the repository and patterns therein. All of the improvements to the official packages have been released and I deleted a ton of code that we don't need nor want to support anymore.

**Comment by manan19** [comment]
Nice!

Are the recommended patterns documented?

**Comment by jacobrosenthal** [comment]
The biggest thing is not hardcoding stuff that we can get from the game, but generally that stuff hasnt actually been available so weve been silently upstreaming all of it so we dont have to hardcode enums and such.

Other than that its just common sense js patterns that were missed during rushed merges.

Hopefully future copy pastes will be just a little more correct :)

**Comment by phated** [comment]
Yeah, as @jacobrosenthal said, it's mostly just a conversion to packages published by the DF team. A lot of things that were updated in this PR were out of date (lvl 7 planet max, no dead space type, etc) by switching over to the official stuff.

This repo started off as the things we needed to make plugins that worked, but once that was proved out, it made more sense for a lot of the utils to come from the official team to stay in-sync.

**Review by jacobrosenthal — APPROVED** [review]
Oops Thought I already approved this. Lets go

**Comment by PawlowskiAdrian** [comment]
Nice, linking to DF hard-coded values and constants is great

**Pull request merged**
