### PR TITLE
chore: Update import/exports

### PR DESCRIPTION
**Pull request by phated**
This doesn't make the plugins compatible with 0.6, but the imports need to be fixed so the `df-plugin-dev-server` can be run against this project using a generic glob like: `content/**/*.js`

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
This does presumably break the plugins for v5 I presume. Its kinda odd to carry them around in inbetween states. maybe commit should say something about being an incomplete update from v5 or something

**Comment by phated** [comment]
I'm wondering if we should just mark all of these as deprecated, since no one came forward to upgrade them for v0.6 round 1 or 2

**Comment by phated** [comment]
@jacobrosenthal how do you want me to resolve? I'm not going to have time to update these to actually work, but have the incorrect module syntax breaks the plugin dev server. Should I deprecate them?

**Comment by jacobrosenthal** [comment]
What if we just change the commit msg to something like "chore: Incomplete v6 update of import/exports"
then at least people looking at that file have a clue

**Comment by phated** [comment]
That's technically incorrect though. This completely updates the import/export - it is just an incomplete upgrade of the plugin, which it doesn't claim to be (nor do they update the version number)

**Comment by jacobrosenthal** [comment]
Then say that in the commit message?

**Pull request merged**
