### PR TITLE
Diplomacy Color Ambassador

### PR DESCRIPTION
**Pull request by Stx69**
Hi all, 
here is my WIP plugin version for diplomacy map update (Friendly/Neutral/Enemy). Issue to add giant players under investigation. Do not hesitate about any feedback / hints...

### CODE REVIEW

**Comment by ichub** [comment]
@Stx69 - did you still want to get this plugin into the showcase?

**Comment by Stx69** [comment]
Hi, yes I hope should be still helpful in dangerous DF universe.. :D let me know if need some changes...

**Comment by snowtigersoft** [comment]
@Stx69 you changed the indent to 4 spaces to exists plugins, which makes it hard to find the real code changes. please change it back to 2 spaces. For the new added plugin, I also suggest to use 2 spaces as indent

**Comment by snowtigersoft** [comment]
I also suggest to cleanup the commits log, thanks.

**Pull request closed without merging**
