### PR TITLE
Add 'heatmap' plugin

### PR DESCRIPTION
**Pull request by pwambach**
The heatmap plugin highlights enemy territories on the board. For each planet a semi transparent circle in the color of the owner and the size of the planet's range is rendered.

Submission for the v0.5 community plugin contest 🎉

screenshot

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Can you try to slim down your screenshot to 20-40kb if it can still look decent? Thanks! Tried it out really cool.

**Comment by pwambach** [comment]
sure, is jpg also ok?

**Comment by phated** [comment]
I think my theme code searches for `screenshot.png` exclusively.

**Comment by pwambach** [comment]
Screenshot is now down to 40kb. Would be cool to add .jpg files in the template because with .png it wasn't easy to get it that small :)

**Pull request merged**
