### PR TITLE
Artifact Market Plugin (WIP)

### PR DESCRIPTION
**Pull request by zk-FARTs**
Just making this PR to ask for some help / tips / advice
Plugin is not done yet but I wanted to get it seen before I make too many bad decisions (It's pretty far along but I'm not against re-writing any or all of it)
No screenshot yet because I plugin isn't finished.
### Smart contract Market.sol: functions buy, list, unlist. admin only functions: newRound, collectFees, changeFee

- buy: user enters artifact ID and sends value of price+fee. price gets sent to the one who listed, artifact gets sent to user, fee stays in contract 
- list:  user enters artifact + price. Transfers an artifact to from the user to the contract and then creates a "listing" with the price provided
- unlist: user enters artifact number. If they were the one to list it, the artifact is returned to them

- newRound: admin enters a timestamp and a new address for the tokens. If it is past the previous stored timestamp the stored timestamp and tokens address are updated to the new ones
- collectFees: if it is past the end of the round, the XDAI balance of the contract (the collected fees) are sent to the admin
- changeFee: admin enters a new fee. The fee gets changed to the new fee (but not too high)

### Frontend
- A table that shows the users withdrawn artifacts+stats with an input area on each row and a button that says "list" Clicking the button will call the list function of the smart contract with that artifacts id and the value of the input as paramaters.
- A footer to that table which shows the artifacts listed on the market that the user put up for sale themselves. Each row has an "unlist" button which on click calls the unlist function of the contract with the artifact chosen as input
- A second table containing all of the other artifacts listed at the market. Each row shows artifact+stats, and at the end of each row there is the price + fee and a button labelled "buy". On click the buy function of the contract is called with the artifact as input and (price+fee) XDAI is sent with this function call
- On clicking any of these buttons and successfully listing, unlisting or buying; the UI updates and the row disappears.
- To get an up to date version of the market there is a "refresh" button that refreshes the whole plugin
- In order for this contract to be able to list the artifacts there is an "approve" button which calls the setApprovalForAll() on the ERC721 artifact contract

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Nice progress! 

This is going to probably be big enough and complex enough to be in your own repo I would expect. 

Check out this plugin/contract combo from @phated and m
https://github.com/projectsophon/df-play-to-earn

Happy to chat more in depth on the discord server btw, Im Jacob Rosenthal#3661

**Comment by modukon** [comment]
It would be nice if the seller could add a small text to the artifact they are selling.
Maybe they are selling the first legendary ever created, they could put this into the description and maybe a link to a proof.

Will we be able to see an image of the artifact?
In what round was the artifact created?
The stat boosts it gives?

Would also be nice (maybe its too much work idk), to be able to auction artifacts.
You put an artifact in and set the selling price, as soon as someone bids the auction starts, then people have 1 week to bid and the highest bid gains the artifact.
I assume the highest bid would need to be locked up by the contract so they can't withdraw it before someone bids more.

**Comment by Stx69** [comment]
this looks how a promising idea....

**Comment by cha0sg0d** [comment]
@zk-FARTs I'm a dfdao member, happy to help w frontend and give more support to you. hmu on discord: cha0sg0d#4787

**Comment by jacobrosenthal** [comment]
This appears to be operational over at 
https://github.com/zk-FARTs/DF-Artifact-Market

Congrats!

Much like broadcast market, Its sadly too big and complex to audit and wouldnt fit in this repo.

But we have the awesome darkforest list now for stuff like this
https://github.com/snowtigersoft/awesome-darkforest

Please add it there and Ill work with dark forest devs to make sure we promote that list from official sources

**Pull request closed without merging**
