### PR TITLE
ensure thread input is read in as a number

### PR DESCRIPTION
**Pull request by 0x-bear**

### CODE REVIEW

**Comment by phated** [comment]
cc @Bind

**Comment by Bind** [comment]
Will check when I get home but looks straightforward enough

**Comment by 0x-bear** [comment]
I couldn't figure out for the life of me *why* this was happening. But any change to the thread input box would result in it being added as a string. Hitting "add" twice would add 2 workers to the pool. Hit the up arrow then down arrow then hit "add" and I get the following error:
```
Uncaught TypeError: Expected `concurrency` to be a number from 1 and up, got `12` (string)
    at PQueue.set concurrency [as concurrency] (p-queue.js:284)
    at updateConcurrency (data:text/javascript…HQgUGx1Z2luOw==:231)
    at addSnarker (data:text/javascript…HQgUGx1Z2luOw==:364)
    at Object.add [as click] (data:text/javascript…HQgUGx1Z2luOw==:312)
    at HTMLButtonElement.C (standalone.module.js:1)
```

**Comment by Bind** [comment]
LGTM

**Pull request merged**
